import { getDb } from './schema.js';
import { initDb } from './schema.js';

const seedGames = [
  {
    name: '卡坦岛',
    name_en: 'Catan',
    image: '',
    description: '在卡坦岛上，玩家通过收集和交易资源来建造道路、定居点和城市。掷骰子决定资源产出，与其他玩家进行激烈的贸易谈判。第一个获得10分的玩家获胜。卡坦岛是现代桌游的代表作，引入了资源管理和交易的核心机制。',
    player_count_min: 3,
    player_count_max: 4,
    duration_per_player: 20,
    difficulty: 2.5,
    rating: 8.5,
    review: '现代桌游的入门神作。贸易环节充满互动与戏剧性，每一局都因骰子和谈判而不同。缺点是初始布局对胜负影响较大。',
    category: '策略',
    published_year: 1995,
  },
  {
    name: '璀璨宝石',
    name_en: 'Splendor',
    image: '',
    description: '玩家扮演文艺复兴时期的宝石商人，通过收集宝石筹码来购买矿山、运输工具和商铺，积累声望点数。游戏节奏明快，需要精打细算每一步的资源积累。',
    player_count_min: 2,
    player_count_max: 4,
    duration_per_player: 10,
    difficulty: 2.0,
    rating: 8.0,
    review: '简约而不简单。配件质感极佳，规则5分钟学会，但策略深度足够反复钻研。2人对弈体验尤佳。',
    category: '策略',
    published_year: 2014,
  },
  {
    name: '谍报风云',
    name_en: 'Codenames',
    image: '',
    description: '两队对抗的词语联想游戏。每队各有一位队长，通过给出一个词语和数字的提示，让队友猜出属于自己方的暗号。队长需要巧妙地将多个词语关联在一起，同时避开对手的词语和刺客牌。',
    player_count_min: 4,
    player_count_max: 8,
    duration_per_player: 5,
    difficulty: 1.0,
    rating: 9.0,
    review: '聚会的王牌游戏。规则简单到30秒就能教完，但每次玩都能爆发出意想不到的笑料。队长的脑洞和队友的默契是胜负关键。',
    category: '聚会',
    published_year: 2015,
  },
  {
    name: '瘟疫危机',
    name_en: 'Pandemic',
    image: '',
    description: '合作类桌游的标杆。玩家组成疾病控制团队，在全球范围内治疗四种致命病毒的爆发。每个玩家拥有独特的角色能力，必须紧密配合，在疫情彻底失控前研发出四种解药。',
    player_count_min: 2,
    player_count_max: 4,
    duration_per_player: 15,
    difficulty: 3.0,
    rating: 8.5,
    review: '合作模式让游戏充满紧张感和团队荣誉感。没有"带新人坐牢"的尴尬，反而越苦越有趣。缺点是可能出现一人指挥全队的情况。',
    category: '合作',
    published_year: 2008,
  },
  {
    name: '七大奇迹',
    name_en: '7 Wonders',
    image: '',
    description: '卡牌轮抽机制的经典代表。玩家领导古代七大奇迹之一的文明，通过三轮选牌来发展军事、科技、文化和商业。每回合同时选牌并传递，几乎没有等待时间。',
    player_count_min: 3,
    player_count_max: 7,
    duration_per_player: 7,
    difficulty: 2.5,
    rating: 8.0,
    review: '7人局也能30分钟内结束的神奇游戏。轮抽机制让每一手都充满两难抉择。计分方式丰富，但初次玩可能需要消化多种符号系统。',
    category: '策略',
    published_year: 2010,
  },
  {
    name: '阿瓦隆',
    name_en: 'The Resistance: Avalon',
    image: '',
    description: '隐藏身份的社交推理游戏。玩家分为亚瑟王的忠臣和莫德雷德的爪牙，通过执行任务来争夺胜利。忠臣需要在没有信息的情况下找出叛徒，而叛徒则要暗中破坏任务同时隐藏身份。',
    player_count_min: 5,
    player_count_max: 10,
    duration_per_player: 5,
    difficulty: 1.5,
    rating: 9.0,
    review: '比狼人杀更纯粹的推理体验。没有玩家淘汰，所有人都能参与全程。梅林与刺客的博弈让每一局都像一场谍战电影。',
    category: '聚会',
    published_year: 2012,
  },
  {
    name: '展翅翱翔',
    name_en: 'Wingspan',
    image: '',
    description: '一款关于鸟类收集的引擎构建游戏。玩家在自己的保护区中吸引各种鸟类，每种鸟都有独特的能力。通过食物、鸟蛋和鸟类卡牌的组合，建立越来越强大的行动链条。',
    player_count_min: 1,
    player_count_max: 5,
    duration_per_player: 15,
    difficulty: 2.5,
    rating: 8.5,
    review: '美工和主题完美融合。翻开每一张鸟牌都像翻开一本自然图鉴。引擎构建的满足感极强，但玩家互动较少，更像各自经营。',
    category: '策略',
    published_year: 2019,
  },
  {
    name: '花砖物语',
    name_en: 'Azul',
    image: '',
    description: '受葡萄牙瓷砖艺术启发的抽象策略游戏。玩家从工厂中选取同色花砖，按照特定规则装饰自己的墙面。完成行、列和同色集的图案可以获得高分。',
    player_count_min: 2,
    player_count_max: 4,
    duration_per_player: 10,
    difficulty: 2.0,
    rating: 8.0,
    review: '颜值与策略兼具的抽象桌游。配件手感极佳，规则的"你拿了就得帮我处理剩下的"非常巧妙，让每一轮都充满博弈。',
    category: '抽象',
    published_year: 2017,
  },
  {
    name: '幽港迷城',
    name_en: 'Gloomhaven',
    image: '',
    description: '史诗级地牢探险合作游戏。玩家扮演雇佣兵，在黑暗奇幻世界中冒险。通过卡牌驱动的战斗系统、逐步解锁的角色和不断展开的故事线，体验数百小时的剧情旅程。',
    player_count_min: 1,
    player_count_max: 4,
    duration_per_player: 30,
    difficulty: 4.5,
    rating: 9.5,
    review: '桌游界的《艾尔登法环》。内容量巨大，战斗系统精妙，但setup和收纳是巨大挑战。适合有固定车队的重度玩家。',
    category: '角色扮演',
    published_year: 2017,
  },
  {
    name: '情书',
    name_en: 'Love Letter',
    image: '',
    description: '极致精简的卡牌推理游戏。每回合摸一张牌、打一张牌，通过角色能力淘汰对手或保护自己。手牌数极少，但每张牌的打出都在向对手传递信息。',
    player_count_min: 2,
    player_count_max: 4,
    duration_per_player: 3,
    difficulty: 1.0,
    rating: 7.5,
    review: '16张牌能玩出如此丰富的心理博弈，桌游极简主义的巅峰。装在口袋里随时开一局，等餐等车绝佳伴侣。',
    category: '聚会',
    published_year: 2012,
  },
];

initDb();
const db = getDb();

const insert = db.prepare(`
  INSERT INTO board_games (name, name_en, image, description, player_count_min, player_count_max, duration_per_player, difficulty, rating, review, category, published_year)
  VALUES (@name, @name_en, @image, @description, @player_count_min, @player_count_max, @duration_per_player, @difficulty, @rating, @review, @category, @published_year)
`);

for (const game of seedGames) {
  insert.run(game);
}

console.log(`✅ 已插入 ${seedGames.length} 款示例桌游数据`);
